#!/bin/bash

#Este script tiene como finalidad modificar la direccion IP para que sea estatica.
sed -i 's/ONBOOT=no/ONBOOT=yes/' /etc/sysconfig/network-scripts/ifcfg-ens3;
sed -i 's/BOOTPROTO=dhcp/BOOTPROTO=static/' /etc/sysconfig/network-scripts/ifcfg-ens3;
echo 'IPADDR=192.168.122.100' >> /etc/sysconfig/network-scripts/ifcfg-ens3;
echo 'NETMASK=255.255.255.0' >> /etc/sysconfig/network-scripts/ifcfg-ens3;
echo 'NETWORK=192.168.122.0' >> /etc/sysconfig/network-scripts/ifcfg-ens3;
echo 'GATEWAY=192.168.122.1' >> /etc/sysconfig/network-scripts/ifcfg-ens3;

